### ISSUE TITLE
python3 ?

### ISSUE THREAD

**Issue by vkuehn** [iksteen/pelicide#2]
This is by far the best solution I saw. Not sure if something like that would be possible with jupyter

is that still under development ?

if so would you mind supporting python3 ?

**Comment by iksteen** [comment]
Hi, thank you for your interest!

Last things first: While I did start a rewrite using python 3 and a new frontend using more modern technology, I never actually finished that. I might pick it up again as I do believe pelicide actually has added value to the pelican ecosystem.

What exactly do you mean with your first statement? Integrating a notebook editor in pelicide? While that would be awesome, I think the amount of work required to implement and maintain that is not something I'm willing to invest (gotta be realistic here).

**Comment by vkuehn** [comment]
currently I work with jupyter lab to edit and see markdown changes. I meant how much compareable is pelicide with jupyters markdown editor ?
sorry for the late reply !

**Comment by iksteen** [comment]
Ah, well, pelicide isn't really compatible with anything in particular. It lets pelican actually render the content and that uses the python 'Markdown' package to render markdown. I have no idea which markdown engine jupyter lab uses.

As for the editing component, pelicide uses two panels, one for editing which also has some markup depending on the markdown context and a right panel that shows a real-time preview. There a demo available here: https://blurringexistence.net/pelicide-demo/ (it uses a slightly different markdown engine because it's implemented in javascript only).

**Comment by vkuehn** [comment]
ok thanks for the clarification. will be fun once you did the transition to python 3
